image:
  repository: quay.io/dimitrovpetar36/app1
  digest: sha256:78e947e3ae65bfb99f45a5561dde1dd2c467e38adf044be376871eb26695b269 # Will be updated by automation
service:
  port: 3001
route:
  enabled: true
  host: app1-am-hub.apps-crc.testing
