version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=app1
    ports:
      - "8081:8080"
  app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=app2
    ports:
      - "8082:8080"
  app3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=app3
    ports:
      - "8083:8080"
  shell:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=shell
    ports:
      - "8084:8080"