apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app3
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: app3
  port:
    targetPort: {{ .Values.service.port }}