image:
  repository: quay.io/dimitrovpetar36/shell
  digest: sha256:d1de880b44d61ab31283799441b1e6edf7c127c3fb96077584394b94dfeacef1 # Will be updated by automation
service:
  port: 3000
route:
  enabled: true
  host: shell-am-hub.apps-crc.testing
