image:
  repository: quay.io/dimitrovpetar36/app3
  digest: sha256:2842474e2260432a2c3ed78bc28421eff250498ce8df0b0ce948252b4b4ff808 # Will be updated by automation
service:
  port: 3003
route:
  enabled: true
  host: app3-am-hub.apps-crc.testing
