image:
  repository: quay.io/dimitrovpetar36/app3
  digest: sha256:f7f7920b0fb04b581eb33a83cd270467183fef6beecb382fad7e048ea3624a9d # Will be updated by automation
service:
  port: 3003
route:
  enabled: true
  host: app3-am-hub.apps-crc.testing
