image:
  repository: quay.io/dimitrovpetar36/app2
  digest: sha256:701dd8ecccdd55cc95228088adabdac8cf090ce6ce3c0c7ca94cba4a4e19b797 # Will be updated by automation
service:
  port: 3002
route:
  enabled: true
  host: app2-am-hub.apps-crc.testing
