image:
  repository: quay.io/dimitrovpetar36/app2
  digest: sha256:7981aef2ca1049df35b459bfe3d7898a9e2f9e818edc6f7800ff048063cb6663 # Will be updated by automation
service:
  port: 3002
route:
  enabled: true
  host: app2-am-hub.apps-crc.testing
